--- #YAML:1.0
name:               Graphics-GnuplotIF-Shortcut
version:            0.03
abstract:           Alternate interface to Graphics::GnuplotIF
author:
    - Boris Zentner <bzm@2bz.de>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Graphics::GnuplotIF:  0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
