# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Graphics-GnuplotIF-Shortcut
version:      0.01
version_from: lib/Graphics/GnuplotIF/Shortcut.pm
installdirs:  site
requires:
    Graphics::GnuplotIF:           0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
